### ISSUE TITLE
upgrade package to support 0.17

### ISSUE THREAD

**Issue by smorele** [circuithub/elm-bootstrap-html#15]
I tried to use this package in an app but I cannot because I run a 0.17 version.

**Comment by rehno-lindeque** [comment]
Unfortunately we're not actively maintaining this package at the moment, but I'm eagerly looking for any new maintainer who would be willing to take over! PR's are also welcome

**Comment by smorele** [comment]
I've cloned the repo but unfortunately new to elm then I'll try to port package to 0.17 but with no guarantee at this time.

**Comment by rehno-lindeque** [comment]
That's all anyone can ask for - thanks for taking a look. I just realized that https://github.com/circuithub/elm-html-shorthand/issues/11 may be a prerequisite for this to happen so you might want to wait on or collaborate with @stkb if he is actively working on it (?).

I may also suggest taking a look at https://github.com/gdotdesign/elm-ui and https://github.com/debois/elm-mdl. I haven't worked with either of these, but elm-ui is looking pretty promising.

**Comment by smorele** [comment]
Thanks for the answer and links. I'm not sure about the elm-shortand necessity, there is no much code from this package used in elm-bootstrap-html then we should remove the dependency.
